<#@ template debug="false" hostspecific="false" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ output extension=".cs" #>

<#
	(string, string)[] tuples =
	{
		("HasValue", "should not have a value"),
		("InvalidReference", "not found in list"),
		("IsDateTime", "should not be a DateTime"),
		("IsDecimal", "should not be a Decimal"),
		("IsDouble", "should not be a double precision floating point number"),
		("IsInteger", "should not be an integer number"),
		("NotDateTime", "is not a DateTime"),
		("NotDecimal", "is not a Decimal"),
		("NotDouble", "is not a double precision floating point number"),
		("NotInfinity", "should be Infinity"),
		("NotInteger", "is not an integer number"),
		("NotNaN", "should be NaN"),
		("NotNull", "should be null"),
		("NotNullOrEmpty", "should be null or empty"),
		("NotNullOrWhiteSpace", "should be null or white space"),
	};
#>

using JJ.Framework.Testing;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// ReSharper disable LocalNameCapturedOnly
// ReSharper disable ConvertToConstant.Local

namespace JJ.Framework.Exceptions.Tests
{
	[TestClass]
	public class ExceptionsWithNameAndValueTests
	{
		private static readonly TestItem _testItem = new TestItem { Parent = new TestItem() };

		<# foreach ((string codeName, string displayText) in tuples) { #>

			[TestMethod]
			public void Test_<#= codeName #>Exception_WithNameOf()
			{
				AssertHelper.ThrowsException<<#= codeName #>Exception>(
					() =>
					{
						int value;

						throw new <#= codeName #>Exception(nameof(value));
					},
					"value <#= displayText #>.");
			}

			[TestMethod]
			public void Test_<#= codeName #>Exception_WithExpression_WithValue()
			{
				AssertHelper.ThrowsException<<#= codeName #>Exception>(
					() =>
					{
						int value = 1;

						throw new <#= codeName #>Exception(() => value);
					},
					"value of 1 <#= displayText #>.");
			}

			[TestMethod]
			public void Test_<#= codeName #>Exception_WithExpression_NoValue()
			{
				AssertHelper.ThrowsException<<#= codeName #>Exception>(
					() =>
					{
						TestItem testItem = _testItem;

						throw new <#= codeName #>Exception(() => testItem.Parent);
					},
					"testItem.Parent <#= displayText #>.");
			}
		<# } #>

	}
}